version: '3'
services:
  middleware:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SALESFORCE_LOGIN_URL=${SALESFORCE_LOGIN_URL}
      - SALESFORCE_USERNAME=${SALESFORCE_USERNAME}
      - SALESFORCE_PASSWORD=${SALESFORCE_PASSWORD}
      - SALESFORCE_AGENT_ID=${SALESFORCE_AGENT_ID}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped 